package com.lmxdawn.other.constant;

/**
 * 短信的区号列表
 */
public interface SmsCountryCodeConstant {

    String LIST_JSON = "[\n" +
            "    {\n" +
            "        \"englishName\":\"Afghanistan\",\n" +
            "        \"chineseName\":\"阿富汗\",\n" +
            "        \"countryCode\":\"AF\",\n" +
            "        \"phoneCode\":\"93\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"englishName\":\"Alaska\",\n" +
            "        \"chineseName\":\"阿拉斯加\",\n" +
            "        \"countryCode\":\"US\",\n" +
            "        \"phoneCode\":\"1907\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"englishName\":\"Albania\",\n" +
            "        \"chineseName\":\"阿尔巴尼亚\",\n" +
            "        \"countryCode\":\"AL\",\n" +
            "        \"phoneCode\":\"355\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"englishName\":\"Algeria\",\n" +
            "        \"chineseName\":\"阿尔及利亚\",\n" +
            "        \"countryCode\":\"DZ\",\n" +
            "        \"phoneCode\":\"213\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"englishName\":\"American Samoa\",\n" +
            "        \"chineseName\":\"美属萨摩亚\",\n" +
            "        \"countryCode\":\"AS\",\n" +
            "        \"phoneCode\":\"1684\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"englishName\":\"Andorra\",\n" +
            "        \"chineseName\":\"安道尔\",\n" +
            "        \"countryCode\":\"AD\",\n" +
            "        \"phoneCode\":\"376\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"englishName\":\"Angola\",\n" +
            "        \"chineseName\":\"安哥拉\",\n" +
            "        \"countryCode\":\"AO\",\n" +
            "        \"phoneCode\":\"244\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"englishName\":\"Anguilla\",\n" +
            "        \"chineseName\":\"安圭拉\",\n" +
            "        \"countryCode\":\"AI\",\n" +
            "        \"phoneCode\":\"1264\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"englishName\":\"Antigua and Barbuda\",\n" +
            "        \"chineseName\":\"安提瓜和巴布达\",\n" +
            "        \"countryCode\":\"AG\",\n" +
            "        \"phoneCode\":\"1268\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"englishName\":\"Argentina\",\n" +
            "        \"chineseName\":\"阿根廷\",\n" +
            "        \"countryCode\":\"AR\",\n" +
            "        \"phoneCode\":\"54\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"englishName\":\"Armenia\",\n" +
            "        \"chineseName\":\"亚美尼亚\",\n" +
            "        \"countryCode\":\"AM\",\n" +
            "        \"phoneCode\":\"374\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"englishName\":\"Aruba\",\n" +
            "        \"chineseName\":\"阿鲁巴\",\n" +
            "        \"countryCode\":\"AW\",\n" +
            "        \"phoneCode\":\"297\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"englishName\":\"Ascension\",\n" +
            "        \"chineseName\":\"阿森松\",\n" +
            "        \"countryCode\":\"SH\",\n" +
            "        \"phoneCode\":\"247\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"englishName\":\"Australia\",\n" +
            "        \"chineseName\":\"澳大利亚\",\n" +
            "        \"countryCode\":\"AU\",\n" +
            "        \"phoneCode\":\"61\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"englishName\":\"Austria\",\n" +
            "        \"chineseName\":\"奥地利\",\n" +
            "        \"countryCode\":\"AT\",\n" +
            "        \"phoneCode\":\"43\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"englishName\":\"Azerbaijan\",\n" +
            "        \"chineseName\":\"阿塞拜疆\",\n" +
            "        \"countryCode\":\"AZ\",\n" +
            "        \"phoneCode\":\"994\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"englishName\":\"Bahamas\",\n" +
            "        \"chineseName\":\"巴哈马\",\n" +
            "        \"countryCode\":\"BS\",\n" +
            "        \"phoneCode\":\"1242\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"englishName\":\"Bahrain\",\n" +
            "        \"chineseName\":\"巴林\",\n" +
            "        \"countryCode\":\"BH\",\n" +
            "        \"phoneCode\":\"973\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"englishName\":\"Bangladesh\",\n" +
            "        \"chineseName\":\"孟加拉国\",\n" +
            "        \"countryCode\":\"BD\",\n" +
            "        \"phoneCode\":\"880\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"englishName\":\"Barbados\",\n" +
            "        \"chineseName\":\"巴巴多斯\",\n" +
            "        \"countryCode\":\"BB\",\n" +
            "        \"phoneCode\":\"1246\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"englishName\":\"Belarus\",\n" +
            "        \"chineseName\":\"白俄罗斯\",\n" +
            "        \"countryCode\":\"BY\",\n" +
            "        \"phoneCode\":\"375\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"englishName\":\"Belgium\",\n" +
            "        \"chineseName\":\"比利时\",\n" +
            "        \"countryCode\":\"BE\",\n" +
            "        \"phoneCode\":\"32\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"englishName\":\"Belize\",\n" +
            "        \"chineseName\":\"伯利兹\",\n" +
            "        \"countryCode\":\"BZ\",\n" +
            "        \"phoneCode\":\"501\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"englishName\":\"Benin\",\n" +
            "        \"chineseName\":\"贝宁\",\n" +
            "        \"countryCode\":\"BJ\",\n" +
            "        \"phoneCode\":\"229\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"englishName\":\"Bermuda\",\n" +
            "        \"chineseName\":\"百慕大群岛\",\n" +
            "        \"countryCode\":\"BM\",\n" +
            "        \"phoneCode\":\"1441\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"englishName\":\"Bhutan\",\n" +
            "        \"chineseName\":\"不丹\",\n" +
            "        \"countryCode\":\"BT\",\n" +
            "        \"phoneCode\":\"975\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"englishName\":\"Bolivia\",\n" +
            "        \"chineseName\":\"玻利维亚\",\n" +
            "        \"countryCode\":\"BO\",\n" +
            "        \"phoneCode\":\"591\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"englishName\":\"Bosnia and Herzegovina\",\n" +
            "        \"chineseName\":\"波斯尼亚和黑塞哥维那\",\n" +
            "        \"countryCode\":\"BA\",\n" +
            "        \"phoneCode\":\"387\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"englishName\":\"Botswana\",\n" +
            "        \"chineseName\":\"博茨瓦纳\",\n" +
            "        \"countryCode\":\"BW\",\n" +
            "        \"phoneCode\":\"267\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"englishName\":\"Brazil\",\n" +
            "        \"chineseName\":\"巴西\",\n" +
            "        \"countryCode\":\"BR\",\n" +
            "        \"phoneCode\":\"55\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"englishName\":\"Brunei\",\n" +
            "        \"chineseName\":\"文莱\",\n" +
            "        \"countryCode\":\"BN\",\n" +
            "        \"phoneCode\":\"673\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"englishName\":\"Bulgaria\",\n" +
            "        \"chineseName\":\"保加利亚\",\n" +
            "        \"countryCode\":\"BG\",\n" +
            "        \"phoneCode\":\"359\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"englishName\":\"Burkina Faso\",\n" +
            "        \"chineseName\":\"布基纳法索\",\n" +
            "        \"countryCode\":\"BF\",\n" +
            "        \"phoneCode\":\"226\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"englishName\":\"Burundi\",\n" +
            "        \"chineseName\":\"布隆迪\",\n" +
            "        \"countryCode\":\"BI\",\n" +
            "        \"phoneCode\":\"257\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"englishName\":\"Cambodia\",\n" +
            "        \"chineseName\":\"柬埔寨\",\n" +
            "        \"countryCode\":\"KH\",\n" +
            "        \"phoneCode\":\"855\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"englishName\":\"Cameroon\",\n" +
            "        \"chineseName\":\"喀麦隆\",\n" +
            "        \"countryCode\":\"CM\",\n" +
            "        \"phoneCode\":\"237\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"englishName\":\"Canada\",\n" +
            "        \"chineseName\":\"加拿大\",\n" +
            "        \"countryCode\":\"CA\",\n" +
            "        \"phoneCode\":\"1\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"englishName\":\"Islas Canarias\",\n" +
            "        \"chineseName\":\"加那利群岛\",\n" +
            "        \"countryCode\":\"ES\",\n" +
            "        \"phoneCode\":\"34\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"englishName\":\"Cape Verde\",\n" +
            "        \"chineseName\":\"开普\",\n" +
            "        \"countryCode\":\"CV\",\n" +
            "        \"phoneCode\":\"238\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"englishName\":\"Cayman Islands\",\n" +
            "        \"chineseName\":\"开曼群岛\",\n" +
            "        \"countryCode\":\"KY\",\n" +
            "        \"phoneCode\":\"1345\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"englishName\":\"Central African Republic\",\n" +
            "        \"chineseName\":\"中非共和国\",\n" +
            "        \"countryCode\":\"CF\",\n" +
            "        \"phoneCode\":\"236\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"englishName\":\"Chad\",\n" +
            "        \"chineseName\":\"乍得\",\n" +
            "        \"countryCode\":\"TD\",\n" +
            "        \"phoneCode\":\"235\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"englishName\":\"China\",\n" +
            "        \"chineseName\":\"中国\",\n" +
            "        \"countryCode\":\"CN\",\n" +
            "        \"phoneCode\":\"86\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"englishName\":\"Chile\",\n" +
            "        \"chineseName\":\"智利\",\n" +
            "        \"countryCode\":\"CL\",\n" +
            "        \"phoneCode\":\"56\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"englishName\":\"Christmas Island\",\n" +
            "        \"chineseName\":\"圣诞岛\",\n" +
            "        \"countryCode\":\"CX\",\n" +
            "        \"phoneCode\":\"0061 9164\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"englishName\":\"Cocos Island\",\n" +
            "        \"chineseName\":\"科科斯岛\",\n" +
            "        \"countryCode\":\"CC\",\n" +
            "        \"phoneCode\":\"0061 9162\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"englishName\":\"Colombia\",\n" +
            "        \"chineseName\":\"哥伦比亚\",\n" +
            "        \"countryCode\":\"CO\",\n" +
            "        \"phoneCode\":\"57\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"englishName\":\"Dominican Republic\",\n" +
            "        \"chineseName\":\"多米尼加共和国\",\n" +
            "        \"countryCode\":\"DO\",\n" +
            "        \"phoneCode\":\"1809\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"englishName\":\"Comoros\",\n" +
            "        \"chineseName\":\"科摩罗\",\n" +
            "        \"countryCode\":\"KM\",\n" +
            "        \"phoneCode\":\"269\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"englishName\":\"Republic Of The Congo\",\n" +
            "        \"chineseName\":\"刚果共和国\",\n" +
            "        \"countryCode\":\"CG\",\n" +
            "        \"phoneCode\":\"242\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"englishName\":\"Cook Islands\",\n" +
            "        \"chineseName\":\"库克群岛\",\n" +
            "        \"countryCode\":\"CK\",\n" +
            "        \"phoneCode\":\"682\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"englishName\":\"Costa Rica\",\n" +
            "        \"chineseName\":\"哥斯达黎加\",\n" +
            "        \"countryCode\":\"CR\",\n" +
            "        \"phoneCode\":\"506\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"englishName\":\"Croatia\",\n" +
            "        \"chineseName\":\"克罗地亚\",\n" +
            "        \"countryCode\":\"HR\",\n" +
            "        \"phoneCode\":\"385\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"englishName\":\"Cuba\",\n" +
            "        \"chineseName\":\"古巴\",\n" +
            "        \"countryCode\":\"CU\",\n" +
            "        \"phoneCode\":\"53\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"englishName\":\"Curacao\",\n" +
            "        \"chineseName\":\"库拉索\",\n" +
            "        \"countryCode\":\"CW\",\n" +
            "        \"phoneCode\":\"599\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"englishName\":\"Cyprus\",\n" +
            "        \"chineseName\":\"塞浦路斯\",\n" +
            "        \"countryCode\":\"CY\",\n" +
            "        \"phoneCode\":\"357\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"englishName\":\"Czech\",\n" +
            "        \"chineseName\":\"捷克\",\n" +
            "        \"countryCode\":\"CZ\",\n" +
            "        \"phoneCode\":\"420\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"englishName\":\"Denmark\",\n" +
            "        \"chineseName\":\"丹麦\",\n" +
            "        \"countryCode\":\"DK\",\n" +
            "        \"phoneCode\":\"45\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"englishName\":\"Djibouti\",\n" +
            "        \"chineseName\":\"吉布提\",\n" +
            "        \"countryCode\":\"DJ\",\n" +
            "        \"phoneCode\":\"253\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"englishName\":\"Dominica\",\n" +
            "        \"chineseName\":\"多米尼加\",\n" +
            "        \"countryCode\":\"DM\",\n" +
            "        \"phoneCode\":\"1767\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"englishName\":\"Dominican Republic\",\n" +
            "        \"chineseName\":\"多米尼加共和国\",\n" +
            "        \"countryCode\":\"DO\",\n" +
            "        \"phoneCode\":\"1809\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"englishName\":\"Ecuador\",\n" +
            "        \"chineseName\":\"厄瓜多尔\",\n" +
            "        \"countryCode\":\"EC\",\n" +
            "        \"phoneCode\":\"593\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"englishName\":\"Egypt\",\n" +
            "        \"chineseName\":\"埃及\",\n" +
            "        \"countryCode\":\"EG\",\n" +
            "        \"phoneCode\":\"20\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"englishName\":\"El Salvador\",\n" +
            "        \"chineseName\":\"萨尔瓦多\",\n" +
            "        \"countryCode\":\"SV\",\n" +
            "        \"phoneCode\":\"503\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"englishName\":\"Equatorial Guinea\",\n" +
            "        \"chineseName\":\"赤道几内亚\",\n" +
            "        \"countryCode\":\"GQ\",\n" +
            "        \"phoneCode\":\"240\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"englishName\":\"Eritrea\",\n" +
            "        \"chineseName\":\"厄立特里亚\",\n" +
            "        \"countryCode\":\"ER\",\n" +
            "        \"phoneCode\":\"291\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"englishName\":\"Estonia\",\n" +
            "        \"chineseName\":\"爱沙尼亚\",\n" +
            "        \"countryCode\":\"EE\",\n" +
            "        \"phoneCode\":\"372\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"englishName\":\"Ethiopia\",\n" +
            "        \"chineseName\":\"埃塞俄比亚\",\n" +
            "        \"countryCode\":\"ET\",\n" +
            "        \"phoneCode\":\"251\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"englishName\":\"Falkland Islands\",\n" +
            "        \"chineseName\":\"福克兰群岛\",\n" +
            "        \"countryCode\":\"FK\",\n" +
            "        \"phoneCode\":\"500\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"englishName\":\"Faroe Islands\",\n" +
            "        \"chineseName\":\"法罗群岛\",\n" +
            "        \"countryCode\":\"FO\",\n" +
            "        \"phoneCode\":\"298\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"englishName\":\"Fiji\",\n" +
            "        \"chineseName\":\"斐济\",\n" +
            "        \"countryCode\":\"FJ\",\n" +
            "        \"phoneCode\":\"679\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"englishName\":\"Finland\",\n" +
            "        \"chineseName\":\"芬兰\",\n" +
            "        \"countryCode\":\"FI\",\n" +
            "        \"phoneCode\":\"358\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"englishName\":\"France\",\n" +
            "        \"chineseName\":\"法国\",\n" +
            "        \"countryCode\":\"FR\",\n" +
            "        \"phoneCode\":\"33\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"englishName\":\"French Guiana\",\n" +
            "        \"chineseName\":\"法属圭亚那\",\n" +
            "        \"countryCode\":\"GF\",\n" +
            "        \"phoneCode\":\"594\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"englishName\":\"French Polynesia\",\n" +
            "        \"chineseName\":\"法属波利尼西亚\",\n" +
            "        \"countryCode\":\"PF\",\n" +
            "        \"phoneCode\":\"689\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"englishName\":\"Gabon\",\n" +
            "        \"chineseName\":\"加蓬\",\n" +
            "        \"countryCode\":\"GA\",\n" +
            "        \"phoneCode\":\"241\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"englishName\":\"Gambia\",\n" +
            "        \"chineseName\":\"冈比亚\",\n" +
            "        \"countryCode\":\"GM\",\n" +
            "        \"phoneCode\":\"220\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"englishName\":\"Georgia\",\n" +
            "        \"chineseName\":\"格鲁吉亚\",\n" +
            "        \"countryCode\":\"GE\",\n" +
            "        \"phoneCode\":\"995\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"englishName\":\"Germany\",\n" +
            "        \"chineseName\":\"德国\",\n" +
            "        \"countryCode\":\"DE\",\n" +
            "        \"phoneCode\":\"49\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"englishName\":\"Ghana\",\n" +
            "        \"chineseName\":\"加纳\",\n" +
            "        \"countryCode\":\"GH\",\n" +
            "        \"phoneCode\":\"233\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"englishName\":\"Gibraltar\",\n" +
            "        \"chineseName\":\"直布罗陀\",\n" +
            "        \"countryCode\":\"GI\",\n" +
            "        \"phoneCode\":\"350\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"englishName\":\"Greece\",\n" +
            "        \"chineseName\":\"希腊\",\n" +
            "        \"countryCode\":\"GR\",\n" +
            "        \"phoneCode\":\"30\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"englishName\":\"Greenland\",\n" +
            "        \"chineseName\":\"格陵兰岛\",\n" +
            "        \"countryCode\":\"GL\",\n" +
            "        \"phoneCode\":\"299\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"englishName\":\"Grenada\",\n" +
            "        \"chineseName\":\"格林纳达\",\n" +
            "        \"countryCode\":\"GD\",\n" +
            "        \"phoneCode\":\"1473\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"englishName\":\"Guadeloupe\",\n" +
            "        \"chineseName\":\"瓜德罗普岛\",\n" +
            "        \"countryCode\":\"GP\",\n" +
            "        \"phoneCode\":\"590\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"englishName\":\"Guam\",\n" +
            "        \"chineseName\":\"关岛\",\n" +
            "        \"countryCode\":\"GU\",\n" +
            "        \"phoneCode\":\"1671\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"englishName\":\"Guatemala\",\n" +
            "        \"chineseName\":\"瓜地马拉\",\n" +
            "        \"countryCode\":\"GT\",\n" +
            "        \"phoneCode\":\"502\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"englishName\":\"Guinea\",\n" +
            "        \"chineseName\":\"几内亚\",\n" +
            "        \"countryCode\":\"GN\",\n" +
            "        \"phoneCode\":\"224\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"englishName\":\"Guinea-Bissau\",\n" +
            "        \"chineseName\":\"几内亚比绍共和国\",\n" +
            "        \"countryCode\":\"GW\",\n" +
            "        \"phoneCode\":\"245\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"englishName\":\"Guyana\",\n" +
            "        \"chineseName\":\"圭亚那\",\n" +
            "        \"countryCode\":\"GY\",\n" +
            "        \"phoneCode\":\"592\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"englishName\":\"Haiti\",\n" +
            "        \"chineseName\":\"海地\",\n" +
            "        \"countryCode\":\"HT\",\n" +
            "        \"phoneCode\":\"509\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"englishName\":\"Hawaii\",\n" +
            "        \"chineseName\":\"夏威夷\",\n" +
            "        \"countryCode\":\"US\",\n" +
            "        \"phoneCode\":\"1808\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"englishName\":\"Honduras\",\n" +
            "        \"chineseName\":\"洪都拉斯\",\n" +
            "        \"countryCode\":\"HN\",\n" +
            "        \"phoneCode\":\"504\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"englishName\":\"Hong Kong\",\n" +
            "        \"chineseName\":\"中国香港\",\n" +
            "        \"countryCode\":\"HK\",\n" +
            "        \"phoneCode\":\"852\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"englishName\":\"Hungary\",\n" +
            "        \"chineseName\":\"匈牙利\",\n" +
            "        \"countryCode\":\"HU\",\n" +
            "        \"phoneCode\":\"36\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"englishName\":\"Iceland\",\n" +
            "        \"chineseName\":\"冰岛\",\n" +
            "        \"countryCode\":\"IS\",\n" +
            "        \"phoneCode\":\"354\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"englishName\":\"India\",\n" +
            "        \"chineseName\":\"印度\",\n" +
            "        \"countryCode\":\"IN\",\n" +
            "        \"phoneCode\":\"91\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"englishName\":\"Indonesia\",\n" +
            "        \"chineseName\":\"印度尼西亚\",\n" +
            "        \"countryCode\":\"ID\",\n" +
            "        \"phoneCode\":\"62\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"englishName\":\"Iran\",\n" +
            "        \"chineseName\":\"伊朗\",\n" +
            "        \"countryCode\":\"IR\",\n" +
            "        \"phoneCode\":\"98\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"englishName\":\"Iraq\",\n" +
            "        \"chineseName\":\"伊拉克\",\n" +
            "        \"countryCode\":\"IQ\",\n" +
            "        \"phoneCode\":\"964\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"englishName\":\"Ireland\",\n" +
            "        \"chineseName\":\"爱尔兰\",\n" +
            "        \"countryCode\":\"IE\",\n" +
            "        \"phoneCode\":\"353\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"englishName\":\"Israel\",\n" +
            "        \"chineseName\":\"以色列\",\n" +
            "        \"countryCode\":\"IL\",\n" +
            "        \"phoneCode\":\"972\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"englishName\":\"Italy\",\n" +
            "        \"chineseName\":\"意大利\",\n" +
            "        \"countryCode\":\"IT\",\n" +
            "        \"phoneCode\":\"39\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"englishName\":\"Ivory Coast\",\n" +
            "        \"chineseName\":\"象牙海岸\",\n" +
            "        \"countryCode\":\"CI\",\n" +
            "        \"phoneCode\":\"225\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"englishName\":\"Jamaica\",\n" +
            "        \"chineseName\":\"牙买加\",\n" +
            "        \"countryCode\":\"JM\",\n" +
            "        \"phoneCode\":\"1876\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"englishName\":\"Japan\",\n" +
            "        \"chineseName\":\"日本\",\n" +
            "        \"countryCode\":\"JP\",\n" +
            "        \"phoneCode\":\"81\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"englishName\":\"Jordan\",\n" +
            "        \"chineseName\":\"约旦\",\n" +
            "        \"countryCode\":\"JO\",\n" +
            "        \"phoneCode\":\"962\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"englishName\":\"Kazakhstan\",\n" +
            "        \"chineseName\":\"哈萨克斯坦\",\n" +
            "        \"countryCode\":\"KZ\",\n" +
            "        \"phoneCode\":\"7\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"englishName\":\"Kenya\",\n" +
            "        \"chineseName\":\"肯尼亚\",\n" +
            "        \"countryCode\":\"KE\",\n" +
            "        \"phoneCode\":\"254\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"englishName\":\"Kiribati\",\n" +
            "        \"chineseName\":\"基里巴斯\",\n" +
            "        \"countryCode\":\"KI\",\n" +
            "        \"phoneCode\":\"686\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"englishName\":\"Korea Democratic Rep.\",\n" +
            "        \"chineseName\":\"朝鲜\",\n" +
            "        \"countryCode\":\"KP\",\n" +
            "        \"phoneCode\":\"85\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"englishName\":\"South Korea\",\n" +
            "        \"chineseName\":\"韩国\",\n" +
            "        \"countryCode\":\"KR\",\n" +
            "        \"phoneCode\":\"82\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"englishName\":\"Kuwait\",\n" +
            "        \"chineseName\":\"科威特\",\n" +
            "        \"countryCode\":\"KW\",\n" +
            "        \"phoneCode\":\"965\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"englishName\":\"Kyrgyzstan\",\n" +
            "        \"chineseName\":\"吉尔吉斯斯坦\",\n" +
            "        \"countryCode\":\"KG\",\n" +
            "        \"phoneCode\":\"996\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"englishName\":\"Laos\",\n" +
            "        \"chineseName\":\"老挝\",\n" +
            "        \"countryCode\":\"LA\",\n" +
            "        \"phoneCode\":\"856\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"englishName\":\"Latvia\",\n" +
            "        \"chineseName\":\"拉脱维亚\",\n" +
            "        \"countryCode\":\"LV\",\n" +
            "        \"phoneCode\":\"371\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"englishName\":\"Lebanon\",\n" +
            "        \"chineseName\":\"黎巴嫩\",\n" +
            "        \"countryCode\":\"LB\",\n" +
            "        \"phoneCode\":\"961\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"englishName\":\"Lesotho\",\n" +
            "        \"chineseName\":\"莱索托\",\n" +
            "        \"countryCode\":\"LS\",\n" +
            "        \"phoneCode\":\"266\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"englishName\":\"Liberia\",\n" +
            "        \"chineseName\":\"利比里亚\",\n" +
            "        \"countryCode\":\"LR\",\n" +
            "        \"phoneCode\":\"231\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"englishName\":\"Libya\",\n" +
            "        \"chineseName\":\"利比亚\",\n" +
            "        \"countryCode\":\"LY\",\n" +
            "        \"phoneCode\":\"218\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"englishName\":\"Liechtenstein\",\n" +
            "        \"chineseName\":\"列支敦士登\",\n" +
            "        \"countryCode\":\"LI\",\n" +
            "        \"phoneCode\":\"423\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"englishName\":\"Lithuania\",\n" +
            "        \"chineseName\":\"立陶宛\",\n" +
            "        \"countryCode\":\"LT\",\n" +
            "        \"phoneCode\":\"370\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"englishName\":\"Luxembourg\",\n" +
            "        \"chineseName\":\"卢森堡\",\n" +
            "        \"countryCode\":\"LU\",\n" +
            "        \"phoneCode\":\"352\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"englishName\":\"Macau\",\n" +
            "        \"chineseName\":\"中国澳门\",\n" +
            "        \"countryCode\":\"MO\",\n" +
            "        \"phoneCode\":\"853\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"englishName\":\"Macedonia\",\n" +
            "        \"chineseName\":\"马其顿\",\n" +
            "        \"countryCode\":\"MK\",\n" +
            "        \"phoneCode\":\"389\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"englishName\":\"Madagascar\",\n" +
            "        \"chineseName\":\"马达加斯加\",\n" +
            "        \"countryCode\":\"MG\",\n" +
            "        \"phoneCode\":\"261\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"englishName\":\"Malawi\",\n" +
            "        \"chineseName\":\"马拉维\",\n" +
            "        \"countryCode\":\"MW\",\n" +
            "        \"phoneCode\":\"265\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"englishName\":\"Malaysia\",\n" +
            "        \"chineseName\":\"马来西亚\",\n" +
            "        \"countryCode\":\"MY\",\n" +
            "        \"phoneCode\":\"60\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"englishName\":\"Maldives\",\n" +
            "        \"chineseName\":\"马尔代夫\",\n" +
            "        \"countryCode\":\"MV\",\n" +
            "        \"phoneCode\":\"960\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"englishName\":\"Mali\",\n" +
            "        \"chineseName\":\"马里\",\n" +
            "        \"countryCode\":\"ML\",\n" +
            "        \"phoneCode\":\"223\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"englishName\":\"Malta\",\n" +
            "        \"chineseName\":\"马耳他\",\n" +
            "        \"countryCode\":\"MT\",\n" +
            "        \"phoneCode\":\"356\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"englishName\":\"Marshall Islands\",\n" +
            "        \"chineseName\":\"马绍尔群岛\",\n" +
            "        \"countryCode\":\"MH\",\n" +
            "        \"phoneCode\":\"692\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"englishName\":\"Martinique\",\n" +
            "        \"chineseName\":\"马提尼克\",\n" +
            "        \"countryCode\":\"MQ\",\n" +
            "        \"phoneCode\":\"596\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"englishName\":\"Mauritania\",\n" +
            "        \"chineseName\":\"毛里塔尼亚\",\n" +
            "        \"countryCode\":\"MR\",\n" +
            "        \"phoneCode\":\"222\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"englishName\":\"Mauritius\",\n" +
            "        \"chineseName\":\"毛里求斯\",\n" +
            "        \"countryCode\":\"MU\",\n" +
            "        \"phoneCode\":\"230\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"englishName\":\"Mayotte\",\n" +
            "        \"chineseName\":\"马约特\",\n" +
            "        \"countryCode\":\"YT\",\n" +
            "        \"phoneCode\":\"269\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"englishName\":\"Mexico\",\n" +
            "        \"chineseName\":\"墨西哥\",\n" +
            "        \"countryCode\":\"MX\",\n" +
            "        \"phoneCode\":\"52\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"englishName\":\"Micronesia\",\n" +
            "        \"chineseName\":\"密克罗尼西亚\",\n" +
            "        \"countryCode\":\"FM\",\n" +
            "        \"phoneCode\":\"691\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"englishName\":\"Moldova\",\n" +
            "        \"chineseName\":\"摩尔多瓦\",\n" +
            "        \"countryCode\":\"MD\",\n" +
            "        \"phoneCode\":\"373\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"englishName\":\"Monaco\",\n" +
            "        \"chineseName\":\"摩纳哥\",\n" +
            "        \"countryCode\":\"MC\",\n" +
            "        \"phoneCode\":\"377\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"englishName\":\"Mongolia\",\n" +
            "        \"chineseName\":\"蒙古\",\n" +
            "        \"countryCode\":\"MN\",\n" +
            "        \"phoneCode\":\"976\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"englishName\":\"Montenegro\",\n" +
            "        \"chineseName\":\"黑山\",\n" +
            "        \"countryCode\":\"ME\",\n" +
            "        \"phoneCode\":\"382\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"englishName\":\"Montserrat\",\n" +
            "        \"chineseName\":\"蒙特塞拉特岛\",\n" +
            "        \"countryCode\":\"MS\",\n" +
            "        \"phoneCode\":\"1664\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"englishName\":\"Morocco\",\n" +
            "        \"chineseName\":\"摩洛哥\",\n" +
            "        \"countryCode\":\"MA\",\n" +
            "        \"phoneCode\":\"212\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"englishName\":\"Mozambique\",\n" +
            "        \"chineseName\":\"莫桑比克\",\n" +
            "        \"countryCode\":\"MZ\",\n" +
            "        \"phoneCode\":\"258\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"englishName\":\"Myanmar\",\n" +
            "        \"chineseName\":\"缅甸\",\n" +
            "        \"countryCode\":\"MM\",\n" +
            "        \"phoneCode\":\"95\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"englishName\":\"Namibia\",\n" +
            "        \"chineseName\":\"纳米比亚\",\n" +
            "        \"countryCode\":\"NA\",\n" +
            "        \"phoneCode\":\"264\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"englishName\":\"Nauru\",\n" +
            "        \"chineseName\":\"拿鲁岛\",\n" +
            "        \"countryCode\":\"NR\",\n" +
            "        \"phoneCode\":\"674\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"englishName\":\"Nepal\",\n" +
            "        \"chineseName\":\"尼泊尔\",\n" +
            "        \"countryCode\":\"NP\",\n" +
            "        \"phoneCode\":\"977\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"englishName\":\"Netherlands\",\n" +
            "        \"chineseName\":\"荷兰\",\n" +
            "        \"countryCode\":\"NL\",\n" +
            "        \"phoneCode\":\"31\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"englishName\":\"New Caledonia\",\n" +
            "        \"chineseName\":\"新喀里多尼亚\",\n" +
            "        \"countryCode\":\"NC\",\n" +
            "        \"phoneCode\":\"687\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"englishName\":\"New Zealand\",\n" +
            "        \"chineseName\":\"新西兰\",\n" +
            "        \"countryCode\":\"NZ\",\n" +
            "        \"phoneCode\":\"64\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"englishName\":\"Nicaragua\",\n" +
            "        \"chineseName\":\"尼加拉瓜\",\n" +
            "        \"countryCode\":\"NI\",\n" +
            "        \"phoneCode\":\"505\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"englishName\":\"Niger\",\n" +
            "        \"chineseName\":\"尼日尔\",\n" +
            "        \"countryCode\":\"NE\",\n" +
            "        \"phoneCode\":\"227\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"englishName\":\"Nigeria\",\n" +
            "        \"chineseName\":\"尼日利亚\",\n" +
            "        \"countryCode\":\"NG\",\n" +
            "        \"phoneCode\":\"234\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"englishName\":\"Niue Island\",\n" +
            "        \"chineseName\":\"纽埃岛(新)\",\n" +
            "        \"countryCode\":\"NU\",\n" +
            "        \"phoneCode\":\"683\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"englishName\":\"Norfolk Island\",\n" +
            "        \"chineseName\":\"诺福克岛(澳)\",\n" +
            "        \"countryCode\":\"NF\",\n" +
            "        \"phoneCode\":\"6723\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"englishName\":\"Norway\",\n" +
            "        \"chineseName\":\"挪威\",\n" +
            "        \"countryCode\":\"NO\",\n" +
            "        \"phoneCode\":\"47\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"englishName\":\"Oman\",\n" +
            "        \"chineseName\":\"阿曼\",\n" +
            "        \"countryCode\":\"OM\",\n" +
            "        \"phoneCode\":\"968\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"englishName\":\"Palau\",\n" +
            "        \"chineseName\":\"帕劳\",\n" +
            "        \"countryCode\":\"PW\",\n" +
            "        \"phoneCode\":\"680\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"englishName\":\"Panama\",\n" +
            "        \"chineseName\":\"巴拿马\",\n" +
            "        \"countryCode\":\"PA\",\n" +
            "        \"phoneCode\":\"507\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"englishName\":\"Papua New Guinea\",\n" +
            "        \"chineseName\":\"巴布亚新几内亚\",\n" +
            "        \"countryCode\":\"PG\",\n" +
            "        \"phoneCode\":\"675\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"englishName\":\"Paraguay\",\n" +
            "        \"chineseName\":\"巴拉圭\",\n" +
            "        \"countryCode\":\"PY\",\n" +
            "        \"phoneCode\":\"595\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"englishName\":\"Peru\",\n" +
            "        \"chineseName\":\"秘鲁\",\n" +
            "        \"countryCode\":\"PE\",\n" +
            "        \"phoneCode\":\"51\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"englishName\":\"Philippines\",\n" +
            "        \"chineseName\":\"菲律宾\",\n" +
            "        \"countryCode\":\"PH\",\n" +
            "        \"phoneCode\":\"63\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"englishName\":\"Poland\",\n" +
            "        \"chineseName\":\"波兰\",\n" +
            "        \"countryCode\":\"PL\",\n" +
            "        \"phoneCode\":\"48\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"englishName\":\"Portugal\",\n" +
            "        \"chineseName\":\"葡萄牙\",\n" +
            "        \"countryCode\":\"PT\",\n" +
            "        \"phoneCode\":\"351\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"englishName\":\"Pakistan\",\n" +
            "        \"chineseName\":\"巴基斯坦\",\n" +
            "        \"countryCode\":\"PK\",\n" +
            "        \"phoneCode\":\"92\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"englishName\":\"Puerto Rico\",\n" +
            "        \"chineseName\":\"波多黎各\",\n" +
            "        \"countryCode\":\"PR\",\n" +
            "        \"phoneCode\":\"1787\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"englishName\":\"Qatar\",\n" +
            "        \"chineseName\":\"卡塔尔\",\n" +
            "        \"countryCode\":\"QA\",\n" +
            "        \"phoneCode\":\"974\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"englishName\":\"Réunion Island\",\n" +
            "        \"chineseName\":\"留尼汪\",\n" +
            "        \"countryCode\":\"RE\",\n" +
            "        \"phoneCode\":\"262\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"englishName\":\"Romania\",\n" +
            "        \"chineseName\":\"罗马尼亚\",\n" +
            "        \"countryCode\":\"RO\",\n" +
            "        \"phoneCode\":\"40\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"englishName\":\"Russia\",\n" +
            "        \"chineseName\":\"俄罗斯\",\n" +
            "        \"countryCode\":\"RU\",\n" +
            "        \"phoneCode\":\"7\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"englishName\":\"Rwanda\",\n" +
            "        \"chineseName\":\"卢旺达\",\n" +
            "        \"countryCode\":\"RW\",\n" +
            "        \"phoneCode\":\"250\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"englishName\":\"Samoa,Eastern\",\n" +
            "        \"chineseName\":\"东萨摩亚(美)\",\n" +
            "        \"countryCode\":\"AS\",\n" +
            "        \"phoneCode\":\"684\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"englishName\":\"Samoa\",\n" +
            "        \"chineseName\":\"萨摩亚\",\n" +
            "        \"countryCode\":\"WS\",\n" +
            "        \"phoneCode\":\"685\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"englishName\":\"San Marino\",\n" +
            "        \"chineseName\":\"圣马力诺\",\n" +
            "        \"countryCode\":\"SM\",\n" +
            "        \"phoneCode\":\"378\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"englishName\":\"Saint Pierre and Miquelon\",\n" +
            "        \"chineseName\":\"圣彼埃尔和密克隆岛\",\n" +
            "        \"countryCode\":\"PM\",\n" +
            "        \"phoneCode\":\"508\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"englishName\":\"Sao Tome and Principe\",\n" +
            "        \"chineseName\":\"圣多美和普林西比\",\n" +
            "        \"countryCode\":\"ST\",\n" +
            "        \"phoneCode\":\"239\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"englishName\":\"Saudi Arabia\",\n" +
            "        \"chineseName\":\"沙特阿拉伯\",\n" +
            "        \"countryCode\":\"SA\",\n" +
            "        \"phoneCode\":\"966\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"englishName\":\"Senegal\",\n" +
            "        \"chineseName\":\"塞内加尔\",\n" +
            "        \"countryCode\":\"SN\",\n" +
            "        \"phoneCode\":\"221\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"englishName\":\"Serbia\",\n" +
            "        \"chineseName\":\"塞尔维亚\",\n" +
            "        \"countryCode\":\"RS\",\n" +
            "        \"phoneCode\":\"381\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"englishName\":\"Seychelles\",\n" +
            "        \"chineseName\":\"塞舌尔\",\n" +
            "        \"countryCode\":\"SC\",\n" +
            "        \"phoneCode\":\"248\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"englishName\":\"Sierra Leone\",\n" +
            "        \"chineseName\":\"塞拉利昂\",\n" +
            "        \"countryCode\":\"SL\",\n" +
            "        \"phoneCode\":\"232\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"englishName\":\"Singapore\",\n" +
            "        \"chineseName\":\"新加坡\",\n" +
            "        \"countryCode\":\"SG\",\n" +
            "        \"phoneCode\":\"65\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"englishName\":\"Saint Maarten (Dutch Part)\",\n" +
            "        \"chineseName\":\"圣马丁岛（荷兰部分）\",\n" +
            "        \"countryCode\":\"SX\",\n" +
            "        \"phoneCode\":\"1721\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"englishName\":\"Slovakia\",\n" +
            "        \"chineseName\":\"斯洛伐克\",\n" +
            "        \"countryCode\":\"SK\",\n" +
            "        \"phoneCode\":\"421\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"englishName\":\"Slovenia\",\n" +
            "        \"chineseName\":\"斯洛文尼亚\",\n" +
            "        \"countryCode\":\"SI\",\n" +
            "        \"phoneCode\":\"386\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"englishName\":\"Solomon Islands\",\n" +
            "        \"chineseName\":\"所罗门群岛\",\n" +
            "        \"countryCode\":\"SB\",\n" +
            "        \"phoneCode\":\"677\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"englishName\":\"Somalia\",\n" +
            "        \"chineseName\":\"索马里\",\n" +
            "        \"countryCode\":\"SO\",\n" +
            "        \"phoneCode\":\"252\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"englishName\":\"South Africa\",\n" +
            "        \"chineseName\":\"南非\",\n" +
            "        \"countryCode\":\"ZA\",\n" +
            "        \"phoneCode\":\"27\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"englishName\":\"Spain\",\n" +
            "        \"chineseName\":\"西班牙\",\n" +
            "        \"countryCode\":\"ES\",\n" +
            "        \"phoneCode\":\"34\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"englishName\":\"Sri Lanka\",\n" +
            "        \"chineseName\":\"斯里兰卡\",\n" +
            "        \"countryCode\":\"LK\",\n" +
            "        \"phoneCode\":\"94\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"englishName\":\"St.Helena\",\n" +
            "        \"chineseName\":\"圣赫勒拿\",\n" +
            "        \"countryCode\":\"SH\",\n" +
            "        \"phoneCode\":\"290\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"englishName\":\"Saint Lucia\",\n" +
            "        \"chineseName\":\"圣露西亚\",\n" +
            "        \"countryCode\":\"LC\",\n" +
            "        \"phoneCode\":\"1758\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"englishName\":\"Saint Vincent and The Grenadines\",\n" +
            "        \"chineseName\":\"圣文森特和格林纳丁斯\",\n" +
            "        \"countryCode\":\"VC\",\n" +
            "        \"phoneCode\":\"1784\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"englishName\":\"Sudan\",\n" +
            "        \"chineseName\":\"苏丹\",\n" +
            "        \"countryCode\":\"SD\",\n" +
            "        \"phoneCode\":\"249\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"englishName\":\"Suriname\",\n" +
            "        \"chineseName\":\"苏里南\",\n" +
            "        \"countryCode\":\"SR\",\n" +
            "        \"phoneCode\":\"597\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"englishName\":\"Swaziland\",\n" +
            "        \"chineseName\":\"斯威士兰\",\n" +
            "        \"countryCode\":\"SZ\",\n" +
            "        \"phoneCode\":\"268\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"englishName\":\"Sweden\",\n" +
            "        \"chineseName\":\"瑞典\",\n" +
            "        \"countryCode\":\"SE\",\n" +
            "        \"phoneCode\":\"46\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"englishName\":\"Switzerland\",\n" +
            "        \"chineseName\":\"瑞士\",\n" +
            "        \"countryCode\":\"CH\",\n" +
            "        \"phoneCode\":\"41\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"englishName\":\"Syria\",\n" +
            "        \"chineseName\":\"叙利亚\",\n" +
            "        \"countryCode\":\"SY\",\n" +
            "        \"phoneCode\":\"963\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"englishName\":\"Taiwan\",\n" +
            "        \"chineseName\":\"中国台湾\",\n" +
            "        \"countryCode\":\"TW\",\n" +
            "        \"phoneCode\":\"886\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"englishName\":\"Tajikistan\",\n" +
            "        \"chineseName\":\"塔吉克斯坦\",\n" +
            "        \"countryCode\":\"TJ\",\n" +
            "        \"phoneCode\":\"992\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"englishName\":\"Tanzania\",\n" +
            "        \"chineseName\":\"坦桑尼亚\",\n" +
            "        \"countryCode\":\"TZ\",\n" +
            "        \"phoneCode\":\"255\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"englishName\":\"Thailand\",\n" +
            "        \"chineseName\":\"泰国\",\n" +
            "        \"countryCode\":\"TH\",\n" +
            "        \"phoneCode\":\"66\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"englishName\":\"Timor-Leste\",\n" +
            "        \"chineseName\":\"东帝汶\",\n" +
            "        \"countryCode\":\"TL\",\n" +
            "        \"phoneCode\":\"670\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"englishName\":\"United Arab Emirates\",\n" +
            "        \"chineseName\":\"阿拉伯联合酋长国\",\n" +
            "        \"countryCode\":\"AE\",\n" +
            "        \"phoneCode\":\"971\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"englishName\":\"Togo\",\n" +
            "        \"chineseName\":\"多哥\",\n" +
            "        \"countryCode\":\"TG\",\n" +
            "        \"phoneCode\":\"228\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"englishName\":\"Tokelau Is.\",\n" +
            "        \"chineseName\":\"托克劳群岛(新)\",\n" +
            "        \"countryCode\":\"TK\",\n" +
            "        \"phoneCode\":\"690\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"englishName\":\"Tonga\",\n" +
            "        \"chineseName\":\"汤加\",\n" +
            "        \"countryCode\":\"TO\",\n" +
            "        \"phoneCode\":\"676\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"englishName\":\"Trinidad and Tobago\",\n" +
            "        \"chineseName\":\"特立尼达和多巴哥\",\n" +
            "        \"countryCode\":\"TT\",\n" +
            "        \"phoneCode\":\"1868\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"englishName\":\"Tunisia\",\n" +
            "        \"chineseName\":\"突尼斯\",\n" +
            "        \"countryCode\":\"TN\",\n" +
            "        \"phoneCode\":\"216\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"englishName\":\"Turkey\",\n" +
            "        \"chineseName\":\"土耳其\",\n" +
            "        \"countryCode\":\"TR\",\n" +
            "        \"phoneCode\":\"90\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"englishName\":\"Turkmenistan\",\n" +
            "        \"chineseName\":\"土库曼斯坦\",\n" +
            "        \"countryCode\":\"TM\",\n" +
            "        \"phoneCode\":\"993\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"englishName\":\"Turks and Caicos Islands\",\n" +
            "        \"chineseName\":\"特克斯和凯科斯群岛\",\n" +
            "        \"countryCode\":\"TC\",\n" +
            "        \"phoneCode\":\"1649\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"englishName\":\"Tuvalu\",\n" +
            "        \"chineseName\":\"图瓦卢\",\n" +
            "        \"countryCode\":\"TK\",\n" +
            "        \"phoneCode\":\"688\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"englishName\":\"United States\",\n" +
            "        \"chineseName\":\"美国\",\n" +
            "        \"countryCode\":\"US\",\n" +
            "        \"phoneCode\":\"1\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"englishName\":\"Uganda\",\n" +
            "        \"chineseName\":\"乌干达\",\n" +
            "        \"countryCode\":\"UG\",\n" +
            "        \"phoneCode\":\"256\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"englishName\":\"Ukraine\",\n" +
            "        \"chineseName\":\"乌克兰\",\n" +
            "        \"countryCode\":\"UA\",\n" +
            "        \"phoneCode\":\"380\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"englishName\":\"United Kingdom\",\n" +
            "        \"chineseName\":\"英国\",\n" +
            "        \"countryCode\":\"GB\",\n" +
            "        \"phoneCode\":\"44\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"englishName\":\"Uruguay\",\n" +
            "        \"chineseName\":\"乌拉圭\",\n" +
            "        \"countryCode\":\"UY\",\n" +
            "        \"phoneCode\":\"598\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"englishName\":\"Uzbekistan\",\n" +
            "        \"chineseName\":\"乌兹别克斯坦\",\n" +
            "        \"countryCode\":\"UZ\",\n" +
            "        \"phoneCode\":\"998\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"englishName\":\"Vanuatu\",\n" +
            "        \"chineseName\":\"瓦努阿图\",\n" +
            "        \"countryCode\":\"VU\",\n" +
            "        \"phoneCode\":\"678\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"englishName\":\"Venezuela\",\n" +
            "        \"chineseName\":\"委内瑞拉\",\n" +
            "        \"countryCode\":\"VE\",\n" +
            "        \"phoneCode\":\"58\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"englishName\":\"Vietnam\",\n" +
            "        \"chineseName\":\"越南\",\n" +
            "        \"countryCode\":\"VN\",\n" +
            "        \"phoneCode\":\"84\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"englishName\":\"Virgin Islands, British\",\n" +
            "        \"chineseName\":\"英属处女群岛\",\n" +
            "        \"countryCode\":\"VG\",\n" +
            "        \"phoneCode\":\"1340\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"englishName\":\"Virgin Islands, US\",\n" +
            "        \"chineseName\":\"美属维尔京群岛\",\n" +
            "        \"countryCode\":\"VI\",\n" +
            "        \"phoneCode\":\"1284\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"englishName\":\"Wake I.\",\n" +
            "        \"chineseName\":\"威克岛(美)\",\n" +
            "        \"countryCode\":\"UM\",\n" +
            "        \"phoneCode\":\"1808\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"englishName\":\"Yemen\",\n" +
            "        \"chineseName\":\"也门\",\n" +
            "        \"countryCode\":\"YE\",\n" +
            "        \"phoneCode\":\"967\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"englishName\":\"Zambia\",\n" +
            "        \"chineseName\":\"赞比亚\",\n" +
            "        \"countryCode\":\"ZM\",\n" +
            "        \"phoneCode\":\"260\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"englishName\":\"Zanzibar\",\n" +
            "        \"chineseName\":\"桑给巴尔\",\n" +
            "        \"countryCode\":\"TZ\",\n" +
            "        \"phoneCode\":\"259\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"englishName\":\"Zimbabwe\",\n" +
            "        \"chineseName\":\"津巴布韦\",\n" +
            "        \"countryCode\":\"ZW\",\n" +
            "        \"phoneCode\":\"263\"\n" +
            "    }\n" +
            "]";

}
